/**
 * Created with JetBrains PhpStorm.
 * User: xuheng
 * Date: 12-8-8
 * Time: 下午2:00
 * To change this template use File | Settings | File Templates.
 */
var templates = [{
    "pre": "pre0.png",
    'title': lang.空白模板,
    'preHtml': '<p class="ue_t">&nbsp;欢迎使用web版幻灯片编辑器！</p>',
    "html": '<p class="ue_t">欢迎使用web版幻灯片编辑器！</p>'

}, {
    "pre": "ppt1.png",
    'title': lang.模板1,
    'preHtml': '<h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:none;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;"><br/></span></h1><p><span style="color:#c0504d;"><br/></span></p><p><span style="color:#c0504d;"><br/></span></p><p><span  style="color:#c0504d;"><br/></span></p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:none;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[键入文档标题]</span></h1><p style="text-align: center;"><strong class="ue_t">[键入文档副标题]</strong></p>',
    'html': '<h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:none;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;"><br/></span></h1><p><span style="color:#c0504d;"><br/></span></p><p><span style="color:#c0504d;"><br/></span></p><p><span  style="color:#c0504d;"><br/></span></p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:none;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">[键入文档标题]</span></h1><p style="text-align: center;"><strong class="ue_t">[键入文档副标题]</strong></p>',
},{
    "pre": "pre1.png",
    'title': lang.blog,
    'preHtml':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">深入理解Range</span></h1><p style="text-align:center;"><strong class=" ">编辑器二次开发</strong></p><h3><span class=" " style="font-family:幼圆">什么是Range</span></h3><p style="text-indent:2em;">    对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。</p><p><br/></p><h3><span class=" " style="font-family:幼圆">Range能干什么</span></h3><p style="text-indent:2em;">    在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。</p><p><br/></p>',
    'html':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">深入理解Range</span></h1><p style="text-align:center;"><strong class=" ">编辑器二次开发</strong></p><h3><span class=" " style="font-family:幼圆">什么是Range</span></h3><p style="text-indent:2em;">    对于“插入”选项卡上的库，在设计时都充分考虑了其中的项与文档整体外观的协调性。</p><p><br/></p><h3><span class=" " style="font-family:幼圆">Range能干什么</span></h3><p style="text-indent:2em;">    在“开始”选项卡上，通过从快速样式库中为所选文本选择一种外观，您可以方便地更改文档中所选文本的格式。</p><p><br/></p>',
}, {
    "pre": "pre2.png",
    'title': lang.resume,
    'preHtml':'<h1 label="Title left" name="tl" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;"><span style="color:#e36c09;" class="ue_t">[此处键入简历标题]</span></h1><p><span style="color:#e36c09;"><br/></span></p><table width="100%" border="1" bordercolor="#95B3D7" style="border-collapse:collapse;"><tbody><tr class="firstRow"><td width="200" style="text-align:center;" class="ue_t">【此处插入照片】</td><td><p><br/></p><p>联系电话：<span class="ue_t">[键入您的电话]</span></p><p><br/></p><p>电子邮件：<span class="ue_t">[键入您的电子邮件地址]</span></p><p><br/></p><p>家庭住址：<span class="ue_t">[键入您的地址]</span></p><p><br/></p></td></tr></tbody></table><h3><span style="color:#e36c09;font-size:20px;">目标职位</span></h3><p style="text-indent:2em;" class="ue_t">[此处键入您的期望职位]</p><h3><span style="color:#e36c09;font-size:20px;">学历</span></h3><p><span style="display:none;line-height:0px;" id="_baidu_bookmark_start_26">﻿</span></p><ol style="list-style-type: decimal;" class=" list-paddingleft-2"><li><p><span class="ue_t">[键入起止时间]</span><span class="ue_t">[键入学校名称]</span><span class="ue_t">[键入所学专业]</span><span class="ue_t">[键入所获学位]</span></p></li></ol><h3><span style="color:#e36c09;font-size:20px;" class="ue_t">工作经验</span></h3><ol style="list-style-type: decimal;" class=" list-paddingleft-2"><li><p><span class="ue_t">[键入起止时间]</span><span class="ue_t">[键入公司名称]</span><span class="ue_t">[键入职位名称]</span></p></li></ol>',
    'html':'<h1 label="Title left" name="tl" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;"><span style="color:#e36c09;" class="ue_t">[此处键入简历标题]</span></h1><p><span style="color:#e36c09;"><br/></span></p><table width="100%" border="1" bordercolor="#95B3D7" style="border-collapse:collapse;"><tbody><tr class="firstRow"><td width="200" style="text-align:center;" class="ue_t">【此处插入照片】</td><td><p><br/></p><p>联系电话：<span class="ue_t">[键入您的电话]</span></p><p><br/></p><p>电子邮件：<span class="ue_t">[键入您的电子邮件地址]</span></p><p><br/></p><p>家庭住址：<span class="ue_t">[键入您的地址]</span></p><p><br/></p></td></tr></tbody></table><h3><span style="color:#e36c09;font-size:20px;">目标职位</span></h3><p style="text-indent:2em;" class="ue_t">[此处键入您的期望职位]</p><h3><span style="color:#e36c09;font-size:20px;">学历</span></h3><p><span style="display:none;line-height:0px;" id="_baidu_bookmark_start_26">﻿</span></p><ol style="list-style-type: decimal;" class=" list-paddingleft-2"><li><p><span class="ue_t">[键入起止时间]</span><span class="ue_t">[键入学校名称]</span><span class="ue_t">[键入所学专业]</span><span class="ue_t">[键入所获学位]</span></p></li></ol><h3><span style="color:#e36c09;font-size:20px;" class="ue_t">工作经验</span></h3><ol style="list-style-type: decimal;" class=" list-paddingleft-2"><li><p><span class="ue_t">[键入起止时间]</span><span class="ue_t">[键入公司名称]</span><span class="ue_t">[键入职位名称]</span></p></li></ol>',
}, {
    "pre":"pre3.png",
        'title':lang.richText,
        'preHtml':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;" class="ue_t">    [此处键入文章标题]</h1><p><img src="http://img.baidu.com/hi/youa/y_0034.gif" width="150" height="100" border="0" hspace="0" vspace="0" style="width:150px;height:100px;float:left;"/>图文混排方法</p><p>    图片居左，文字围绕图片排版</p><p>    方法：在文字前面插入图片，设置居左对齐，然后即可在右边输入多行文</p><p><br/></p><p><img src="http://img.baidu.com/hi/youa/y_0040.gif" width="100" height="100" border="0" hspace="0" vspace="0" style="width:100px;height:100px;float:right;"/></p><p>    还有没有什么其他的环绕方式呢？这里是居右环绕</p><p><br/></p><p>欢迎大家多多尝试，为PPT智能模板提供更多高质量模板！</p><p><br/></p>',
        'html':'<h1 label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;" class="ue_t">    [此处键入文章标题]</h1><p><img src="http://img.baidu.com/hi/youa/y_0034.gif" width="150" height="100" border="0" hspace="0" vspace="0" style="width:150px;height:100px;float:left;"/>图文混排方法</p><p>    图片居左，文字围绕图片排版</p><p>    方法：在文字前面插入图片，设置居左对齐，然后即可在右边输入多行文</p><p><br/></p><p><img src="http://img.baidu.com/hi/youa/y_0040.gif" width="100" height="100" border="0" hspace="0" vspace="0" style="width:100px;height:100px;float:right;"/></p><p>    还有没有什么其他的环绕方式呢？这里是居右环绕</p><p><br/></p><p>欢迎大家多多尝试，为PPT智能模板提供更多高质量模板！</p><p><br/></p>',
    },
    {
        "pre":"pre4.png",
        'title':lang.sciPapers,
        'preHtml':'<h2 style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;text-align:center;" class="ue_t">[键入文章标题]</h2><p><strong><span style="font-size:12px;">摘要</span></strong><span style="font-size:12px;" class="ue_t">：这里可以输入很长很长很长很长很长很长很长很长很差的摘要</span></p><p style="line-height:1.5em;"><strong>标题 1</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">这里可以输入很多内容，可以图文混排，可以有列表等。</span></p><p style="line-height:1.5em;"><strong>标题 2</strong></p><ol style="list-style-type:lower-alpha;"><li><p class="ue_t">列表 1</p></li><li><p class="ue_t">列表 2</p></li><ol style="list-style-type:lower-roman;"><li><p class="ue_t">多级列表 1</p></li><li><p class="ue_t">多级列表 2</p></li></ol><li><p class="ue_t">列表 3<br /></p></li></ol><p style="line-height:1.5em;"><strong>标题 3</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">来个文字图文混排的</span></p><p style="text-indent:2em;"><br /></p>',
        'html':'<h2 style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;margin:0px 0px 10px;text-align:center;" class="ue_t">[键入文章标题]</h2><p><strong><span style="font-size:12px;">摘要</span></strong><span style="font-size:12px;" class="ue_t">：这里可以输入很长很长很长很长很长很长很长很长很差的摘要</span></p><p style="line-height:1.5em;"><strong>标题 1</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">这里可以输入很多内容，可以图文混排，可以有列表等。</span></p><p style="line-height:1.5em;"><strong>标题 2</strong></p><ol style="list-style-type:lower-alpha;"><li><p class="ue_t">列表 1</p></li><li><p class="ue_t">列表 2</p></li><ol style="list-style-type:lower-roman;"><li><p class="ue_t">多级列表 1</p></li><li><p class="ue_t">多级列表 2</p></li></ol><li><p class="ue_t">列表 3<br /></p></li></ol><p style="line-height:1.5em;"><strong>标题 3</strong></p><p style="text-indent:2em;"><span style="font-size:14px;" class="ue_t">来个文字图文混排的</span></p><p style="text-indent:2em;"><br /></p>',
    }];